.TH SSLSNIFF 1
.SH NAME
sslsniff \- analyze ssl connections and write information about them

.SH SYNOPSIS
.B sslsniff
[\fB\-i\fI \f INTERFACE_NAME\fR]
[\fB\-r\fI \f PCAPNG_FILE_NAME\fR]
[\fB\--help]

.SH DESCRIPTION
It`s basic tool for analyze packet.
You can choose if sslsniff will read file or sniffing on specific interface.
It find ssl connections and store informations about them.
It work only if packets arive in correct sequence.
If comunication si closed, it print information on stdout.
Output format: <timestamp>,<client ip>,<client port>,<server ip>,<SNI>,<bytes>,<packets>,<duration sec>

.SH OPTIONS
.TP
.BR \-i\ \fI INTERFACE_NAME\fR
Start sniffing on interface.
.TP
.BR \-r\ \fI PCAPNG_FILE_NAME\fR
Start analyze file.
.TP
.BR \--help \fR
Print help message.
